version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10 # https://circleci.com/docs/2.0/circleci-images/
  working_directory: ~/repo
jobs:
  build:
    <<: *defaults  
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-lock-{{ checksum "yarn.lock" }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/repo/.npmrc
      - run:
          name: Install dependencies
          command: |
            yarn install
      - run:
          name: Test
          command: |
            yarn test
      - run:
          name: Build
          command: |
            yarn build
      - save_cache:
          key: v1-yarn-lock-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  deploy-npm:
    <<: *defaults  
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-lock-{{ checksum "yarn.lock" }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/repo/.npmrc
      - run:
          name: Deploy to npm
          command: |
            yarn install
            yarn build
            yarn publish --patch --message "bumping version - [skip ci]"
            git push
            git push --tags
      - save_cache:
          key: v1-yarn-lock-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: development
      - deploy-npm:
          context: development
          requires:
            - build
          filters:
            branches:
              only: master